### ISSUE TITLE
GithubAction CDの導入

### ISSUE THREAD

**Issue by mayu0130** [mayu0130/Cafe-app#139]
## タスク概要
- Github Actionsを使ってCDを導入する
（pushした時にrenderを通してデプロイするようにする
　※ # で自動デプロイ化は実施済み）

## TODO
- 以下を`render_deploy.yml`に記入

```
name: Render Deploy

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Render Deployment
        uses: ttskch/render-deploy@v1.0.0
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          interval: 60 
          timeout: 600
```

## 参考記事
[[Rails]Github Actionsを使ったCI/CD](https://zenn.dev/redheadchloe/articles/8666b6b93d7647)
[Render.comでのデプロイを行うためのGitHub Actions構築方法](https://qiita.com/ora_yoshito/items/a1e697236e7edbbda7fb)
